/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Feedback: {
      address: "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      "abi": [
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "semaphoreAddress",
                    "type": "address"
                },
                {
                    "internalType": "uint256",
                    "name": "_groupId",
                    "type": "uint256"
                }
            ],
            "stateMutability": "nonpayable",
            "type": "constructor"
        },
        {
            "inputs": [],
            "name": "groupId",
            "outputs": [
                {
                    "internalType": "uint256",
                    "name": "",
                    "type": "uint256"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "uint256",
                    "name": "identityCommitment",
                    "type": "uint256"
                }
            ],
            "name": "joinGroup",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        },
        {
            "inputs": [],
            "name": "semaphore",
            "outputs": [
                {
                    "internalType": "contract ISemaphore",
                    "name": "",
                    "type": "address"
                }
            ],
            "stateMutability": "view",
            "type": "function"
        },
        {
            "inputs": [
                {
                    "internalType": "uint256",
                    "name": "feedback",
                    "type": "uint256"
                },
                {
                    "internalType": "uint256",
                    "name": "merkleTreeRoot",
                    "type": "uint256"
                },
                {
                    "internalType": "uint256",
                    "name": "nullifierHash",
                    "type": "uint256"
                },
                {
                    "internalType": "uint256[8]",
                    "name": "proof",
                    "type": "uint256[8]"
                }
            ],
            "name": "sendFeedback",
            "outputs": [],
            "stateMutability": "nonpayable",
            "type": "function"
        }
    ],
      inheritedFunctions: {},
    },
    SprintVote: {
      address: "0xf5059a5D33d5853360D16C683c16e67980206f36",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "PollCreated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "closePoll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bool",
              name: "_isAnonymous",
              type: "bool",
            },
          ],
          name: "createPoll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
          ],
          name: "getVotes",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_vote",
              type: "uint256",
            },
          ],
          name: "vote",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
